### GET /api/recipes, devolverá un lista con todos los registros
GET http://localhost:5000/api/recipes




### GET /api/recipes?con=vodka, devolverá un lista esta búsqueda







### GET /api/recipes/5f7daa018ec9dfb536781afa busqueda por id
GET http://localhost:5000/api/recipes/634479efcf512d6293015521

### GET /api/recipes?con=vodka, devolverá un lista esta búsqueda
GET http://localhost:5000/api/recipes?con=aaaaa

### GET /api/recipes?con=vodka, devolverá un lista esta búsqueda
GET http://localhost:5000/api/recipes?con=whiskey

### POST /api/recipes, creará un registro nuevo a partir de los parámetros que enviemos con
### el POST, y devolverá el id del registro creado, y sus datos

POST http://localhost:5000/api/recipes
Content-Type: application/json

{ 
    "name":"Prueba de ejercicio con POST", 
    "instructions":"Haciendo Post", 
    "ingredients":[ 
        { "name":"POST", 
        "quantity":{ 
            "quantity":"2", "unit":"oz" 
            } 
        } 
    ], 
    "slug":"POST", 
    "garnish":"POST", 
    "reviews":"POST"
}

### PUT /api/recipes/5f7b4b6204799f5cf837b1e1, modificará el registro a partir de
### los parámetros enviados en el PUT y devolverá el id del registro modificado y sus datos

PUT http://localhost:5000/api/recipes/634479efcf512d6293015521
Content-Type: application/json

{ 
    "name":"Prueba de ejercicio con CCCB", 
    "instructions":"Haciendo CCC", 
    "ingredients":[ 
        { "name":"CCC", 
        "quantity":{ 
            "quantity":"2", "unit":"oz" 
            } 
        } 
    ], 
    "slug":"CCC", 
    "garnish":"CCC", 
    "reviews":"CCC"
}




### DELETE /api/recipes/5f7daa018ec9dfb536781afa, borrara el registro correspondiente
### y devolverá el id del registro borrado

DELETE http://localhost:5000/api/recipes/634479efcf512d6293015527   